; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	L:\Projetos\RPGXP\PHLC Netplay\PHLCServer\PHLCServer\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
